import { WorkHistoryInterface } from "./types";

export const workHistorys: WorkHistoryInterface[] = [
    {
        jobTitle: "Senior Developer",
        company: "iContainers",
        location: "Melbourne, Australia",
        from: "Jan 2022",
        to: "Present",
        summary: "As senior developer my roles and responsibilities are",
        responsibilities: [
            "Designed and implemented a robust data migration mapper from MongoDB to PostgreSQL, ensuring seamless transfer of data from legacy databases",
            "Defined and implemented PostgreSQL schemas based on project requirements, ensuring data integrity and adherence to best practices.",
            "Wrote comprehensive test cases to validate data migration processes, ensuring accuracy, completeness, and reliability of the transferred data",
        ],
        links: [],
        stack: [
            "Typescript",
            "Node",
            "AWS",
            "NestJs",
            "Posgresql",
        ],
    },
    {
        jobTitle: "Lead Full Stack Developer",
        company: "Fusion Startup Engineering Studio formally WeAreNova",
        location: "Islamabad, Pakistan(Remote)",
        from: "Jan 2022",
        to: "Jul 2023",
        summary: "As lead full stack developer my tasks are",
        responsibilities: [
            "Added smart search functionality to the platform, resulted in improved querying, which ultimately led to excellent results.",
            "Improved the algorithm logic of the platform, resulted in improved accuracy in search results of the saas platform.",
            "Refactored old code for more readability.",
            "Translated the UX/UI mockups into pixel perfect and responsive applications",
            "Along with routine development tasks, managed the engineering team",
            "Gave my feedback on product domain and provided technical support in day to day engineering problems.",
        ],
        links: [],
        stack: [
            "Javascript",
            "React",
            "AWS",
            "Node",
            "MySQL",
            "SASS",
            "AdobeXD",
            "DotNet"
        ],
    },
    {
        jobTitle: "React Developer",
        company: "Iplex Pvt Ltd",
        location: "Islamabad, Pakistan",
        from: "Mar 2021",
        to: "Jan 2022",
        summary: "As full stack react developer my achievements and tasks are",
        responsibilities: [
            "Developed applications for tech startups to calculate performance index for investors and founders and included the content needed for Investors and founders to have more insights about the company standing which boosted the engagement by 100%",
            "Included the simulator tool to compare deal terms, increasing the visibility by five times.",
        ],
        links: ["https://app.saaspi.io/deal-simulator"],
        stack: [
            "Typescript",
            "AWS",
            "React",
            "Firebase",
            "Jira",
            "Redux",
            "Material UI",
            "Adobe XD",
        ],
    },
    {
        jobTitle: "Software Engineer",
        company: "Huawei Technologies",
        location: "Islamabad, Pakistan",
        from: "Sep 2019",
        to: "April 2021",
        summary: "As full stack developer my achievements and tasks were:",
        responsibilities: [
            "While working in a team environment, delivered various platforms.",
            "Worked at Middle East Digital Competence Center (ME- DCC) to develop with Huawei OWS cloud and successfully developed various OWS based platforms.  ",
            "Developed dashboards for the Middle East Region of Huawei.",
            "Created RESTful API’s for different requirements. Maintained code using distributed version control system Git and built pipelines with microsoft TFS.",
            "Developed data analysis and selenium-based automation tools in python.",
        ],
        links: [],
        stack: ["Javascript", "ES6", "Vue", "React", "Python", "DotNet"],
    }
];
